# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches: [main]

permissions:
  contents: write # ← gh-pages ブランチへ push するために必要

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_BASE_URL: /portfolio/
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Viteの環境変数をセット
      - name: Export Vite envs to GitHub Actions
        run: |
          echo "VITE_BASE_URL=${{ env.VITE_BASE_URL }}" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          enable_jekyll: false # .nojekyll を置く
          # cname: www.example.com # 独自ドメインの場合のみ
